### ISSUE TITLE
How do i use this in revit?

### ISSUE THREAD

**Issue by aleksandervikdal** [logant/Revit_LegendCopy#1]
Sorry for the newbish question, but I've searched quite a while without getting any closer to the answer.

Shall I install something? It's also two different downloads which one shall i use?

LegendCopy_20160623
OR
Revit_LegendCopy-master

C:\ProgramData\Autodesk\Revit\Addins\2018
Is this where i deploy the addin files?

and

C:\ProgramData\Autodesk\Revit\Addins\2018\Communicator
is this where i deply the dll files?

Thanks for all help

**Comment by logant** [comment]
Revit_LegendCopy-master.zip is the source code to compile it yourself. LegendCopy_20160623.zip is an already compiled version from about three years ago (the last time this repo was updated). So if you don't want to mess about with the source code and compile it yourself, it's best to go with the LegendCopy_20160623.zip file only.

As for installing it, Revit looks for plugins in two primary places: 

C:\ProgramData\Autodesk\Revit\Addins\201#

and

C:\Users\[your-username]\AppData\Roaming\Autodesk\Revit\Addins\201#

The major difference is the first installs plugins for all users, and the second for only the current user. Also most companies have policies in place that prevent typical users from installing to the ProgramData folder, but not to your user profile (second option).

When Revit looks for a plugin in these two places, the only thing Revit initially cares about is the ADDIN file, but the ADDIN file tells Revit where to find the DLL file(s). In this case there an expectation that the ADDIN and DLL files are all located in the same place, ie one of the two folders mentioned previously.

One last caution is that you'll probably need to unblock the files after you download them. This can be unlocking the ZIP file before extracting the DLL and ADDIN files, or by unblocking the individual files separately. Windows will typically block files downloaded from the internet in case you accidentally downloaded something malicious and this blocking will likely prevent the plugin from working.

**Comment by aleksandervikdal** [comment]
It worked! Thanks a ton for the help logant. Saved me for many hours of work. Really apprieciate it.
